controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
# config/routes.yaml
ride_get_all:
    path: /rides
    controller: App\Controller\RideController::getAll
    methods: ['GET']

ride_create:
    path: /rides/createRide
    controller: App\Controller\RideController::createRide
    methods: ['POST']

ride_delete:
    path: /rides/delete/{userId}
    controller: App\Controller\RideController::delete
    methods: ['DELETE']

